using Go = import "/go.capnp";
@0xa23c0346374acc40;  # unique file ID, generated by `capnp id`
$Go.package("books");
$Go.import("books");

struct Book {
	title @0 :Text;
	# Title of the book.

	pageCount @1 :Int32;
	# Number of pages in the book.
}
